const Homeproduct = [
  {
    id: "1",
    name: "Amtec Tv",
    price: "80",
    image: "image/Amtec tv.jpg",
    cat: "tv",
    type: "top",
  },
  {
    id: "2",
    name: "Realme 80cm tv",
    price: "285",
    image: "image/realme 80cm tv.jpg",
    cat: "tv",
    type: "top",
  },
  {
    id: "3",
    name: "Apple-iPhone-14-Pro",
    price: "500",
    image: "image/Apple-iPhone-14-Pro-4.png",
    cat: "phone",
    type: "new",
  },
  {
    id: "4",
    name: "Apple-iPhone",
    price: "400",
    image: "image/mobiles-nav-card-apple2-200323.webp",
    cat: "phone",
    type: "top",
  },
  {
    id: "5",
    name: "Vivo",
    price: "350",
    image: "/image/Vivo.jpg",
    cat: "phone",
    type: "top",
  },
  {
    id: "6",
    name: "Smartphone-Oppo",
    price: "320",
    image:
      "image/Smartphone-Oppo-Find-X3-Lite-6-43-Double-SIM-128-Go-5G-Noir.jpg",
    cat: "phone",
    type: "featured",
  },
  {
    id: "7",
    name: "Gaming Headphone",
    price: "130",
    image: "image/G690 Gaming Headphone.jpg",
    cat: "headphone",
    type: "new",
  },
  {
    id: "8",
    name: "Headphone",
    price: "125",
    image: "image/Headphone.jpg",
    cat: "headphone",
    type: "featured",
  },
  {
    id: "9",
    name: "Headphone-for-Girl",
    price: "128",
    image: "image/Headphone_female.jpg",
    cat: "headphone",
    type: "top",
  },
  {
    id: "10",
    name: "AVITA-LAPTOP",
    price: "650",
    image: "./image/AVITA-LAPTOP.jpg",
    cat: "laptop",
    type: "top",
  },
  {
    id: "11",
    name: "HP_Spectre_x360_14",
    price: "550",
    image: "image/HP_Spectre_x360_14_AKrales_0004.webp",
    cat: "laptop",
    type: "featured",
  },
  {
    id: "12",
    name: "MacBook Pro",
    price: "480",
    image: "image/MacBook Pro.jpg",
    cat: "laptop",
    type: "top",
  },
  {
    id: "13",
    name: "Surface_Laptop_5",
    price: "440",
    image: "image/Surface_Laptop_5_AKrales.webp",
    cat: "laptop",
    type: "featured",
  },
  {
    id: "14",
    name: "Bluetooth speaker",
    price: "125",
    image: "image/Bluetooth speaker.jpg",
    cat: "speaker",
    type: "new",
  },
  {
    id: "15",
    name: "Bluetooth-Speaker",
    price: "130",
    image:
      "image/Bluetooth-Speaker-Wireless-Stereo-5W-TWS-Paring-Portable-Outdoor-IPX7-Waterproof-With-Strap-For-Hooking-Mini.jpg",
    cat: "speaker",
    type: "new",
  },
  {
    id: "16",
    name: "Bluetooth",
    price: "123",
    image: "image/bluetooth.jpg",
    cat: "speaker",
    type: "top",
  },
  {
    id: "17",
    name: "Couple watchs",
    price: "125",
    image: "image/couple watches.jpg",
    cat: "watch",
    type: "top",
  },
  {
    id: "18",
    name: "Male watches",
    price: "120",
    image: "image/Male sport wtches.jpg",
    cat: "watch",
    type: "featured",
  },
  {
    id: "19",
    name: "Steel Watch",
    price: "136",
    image: "image/depositphotos_35187441-stock-photo-watch.jpg",
    cat: "watch",
    type: "top",
  },
  {
    id: "20",
    name: "Watch for girl",
    price: "138",
    image: "image/Watch for girl.jpg",
    cat: "watch",
    type: "new",
  },
  {
    id: "21",
    name: "The 9 Best-Laptop",
    price: "330",
    image: "./image/Laptop-new.jpg",
    cat: "laptop",
    type: "new",
  },
  {
    id: "22",
    name: "Avita-laptop",
    price: "390",
    image: "./image/Avita-laptop-new.jpg",
    cat: "laptop",
    type: "new",
  },
  {
    id: "23",
    name: "Tv-2023",
    price: "190",
    image: "./image/tv.jpg",
    cat: "tv",
    type: "new",
  },

  {
    id: "24",
    name: "Headphone",
    price: "200",
    image: "./image/headphone-new-design.jpg",
    cat: "headphone",
    type: "new",
  },
];

export default Homeproduct;
